name: VPN Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard
        run: sudo apt-get install -y wireguard

      - name: Create config
        run: |
          echo "[Interface]
          Address = 10.0.1.2/32
          PrivateKey = 8PmnB3Omdsa+bkv1ZEjpGgOMp5CIPO6JcKEbm1GQfmo=
          DNS = 8.8.8.8

          [Peer]
          PublicKey = J3k+vf4xU/FZni/gGcPsVCbi2H0GLuA9eHusL3Su2Uo=
          Endpoint = 143.198.219.76:51820
          AllowedIPs = 0.0.0.0/0, ::/0
          PersistentKeepalive = 25" | sudo tee /etc/wireguard/wg0.conf

      - name: Check IP before VPN
        run: curl https://ipinfo.io

      - name: Connect VPN
        run: sudo wg-quick up wg0

      - name: Check handshake
        run: sudo wg show

      - name: Check IP after VPN
        run: curl https://ipinfo.io

      - name: Test internet through VPN
        run: curl --interface wg0 https://ipinfo.io
